const Animations = {
  attentionSeekers: {
    bounce: 'bounce',
    flash: 'flash',
    pulse: 'pulse',
    rubberBand: 'rubberBand',
    shake: 'shake',
    swing: 'swing',
    tada: 'tada',
    wobble: 'wobble',
    jello: 'jello',
    heartBeat: 'heartBeat',
  },
  bouncingEntrances: {
    bounceIn: 'bounceIn',
    bounceInDown: 'bounceInDown',
    bounceInLeft: 'bounceInLeft',
    bounceInRight: 'bounceInRight',
    bounceInUp: 'bounceInUp',
  },
  bouncingExits: {
    bounceOut: 'bounceOut',
    bounceOutDown: 'bounceOutDown',
    bounceOutLeft: 'bounceOutLeft',
    bounceOutRight: 'bounceOutRight',
    bounceOutUp: 'bounceOutUp',
  },
  fadingEntrances: {
    fadeIn: 'fadeIn',
    fadeInDown: 'fadeInDown',
    fadeInDownBig: 'fadeInDownBig',
    fadeInLeft: 'fadeInLeft',
    fadeInLeftBig: 'fadeInLeftBig',
    fadeInRight: 'fadeInRight',
    fadeInRightBig: 'fadeInRightBig',
    fadeInUp: 'fadeInUp',
    fadeInUpBig: 'fadeInUpBig',
  },
  fadingExits: {
    fadeOut: 'fadeOut',
    fadeOutDown: 'fadeOutDown',
    fadeOutDownBig: 'fadeOutDownBig',
    fadeOutLeft: 'fadeOutLeft',
    fadeOutLeftBig: 'fadeOutLeftBig',
    fadeOutRight: 'fadeOutRight',
    fadeOutRightBig: 'fadeOutRightBig',
    fadeOutUp: 'fadeOutUp',
    fadeOutUpBig: 'fadeOutUpBig',
  },
  flippers: {
    flip: 'flip',
    flipInX: 'flipInX',
    flipInY: 'flipInY',
    flipOutX: 'flipOutX',
    flipOutY: 'flipOutY',
  },
  LightSpeed: {
    lightSpeedIn: 'lightSpeedIn',
    lightSpeedOut: 'lightSpeedOut',
  },
  rotatingEntraces: {
    rotateIn: 'rotateIn',
    rotateInDownLeft: 'rotateInDownLeft',
    rotateInDownRight: 'rotateInDownRight',
    rotateInUpLeft: 'rotateInUpLeft',
    rotateInUpRight: 'rotateInUpRght',
  },
  rotatingExits: {
    rotateOut: 'rotateOut',
    rotateOutDownLeft: 'rotateOutDownLeft',
    rotateOutDownRight: 'rotateOutDownRight',
    rotateOutUpLeft: 'rotateOutUpLeft',
    rotateOutUpRight: 'rotateOutUpRight',
  },
  slidingEntrances: {
    slideInUp: 'slideInUp',
    slideInDown: 'slideInDown',
    slideInLeft: 'slideInLeft',
    slideInRight: 'slideInRight',
  },
  slidingExits: {
    slideOutUp: 'slideOutUp',
    slideOUtDown: 'slideOutDown',
    slideOutLeft: 'slideOutLeft',
    slideOutRight: 'slideOutRight',
  },
  zoomEntrances: {
    zoomIn: 'zoomIn',
    zoomInDown: 'zoomInDown',
    zoomInLeft: 'zoomInLeft',
    zoomInRight: 'zoomInRight',
    zoomInUp: 'zoomInUp',
  },
  zoomExits: {
    zoomOut: 'zoomOut',
    zoomOutDown: 'zoomOutDown',
    zoomOutLeft: 'zoomOutLeft',
    zoomOutRight: 'zoomOutRight',
    zoomOutUp: 'zoomOutUp',
  },
  specials: {
    hinge: 'hinge',
    jackInTheBox: 'jackInTheBox',
    rollIn: 'rollIn',
    rollOut: 'rollOut',
  },
};

export default Animations;
